### ISSUE TITLE
Applying custom wi-fi icons from theme

### ISSUE THREAD

**Issue by bokoto** [andrew-bibb/cmst#140] opened 2016-03-15 16:58 UTC
Initial ref. in #98 

Hi Andrew, I know this is a closed one but i am trying to get CMST to work with a different wifi icon theme in Lxqt and following the instructions above. I am running xfwm4 and using Breeze theme as system wide theme. All desktop icons change correctly but the CMST wifi icon remains the same ( hard-coded ). I cant locate any cmst.icon file anywhere. The only other icon that CMST will accept is Faenza but it remains grey and won't change color thru the colorize option. I have tried setting the icon theme from the cli too - to no avail. So far I have tried Breeze, GNOME, Oxygen, none of them working with CMST. What is it that I am missing? Thanks.

Edit: I found the cmst.icon file - however no idea as to how to add/ modify themes , names in there - any help will be appreciated.

**Comment by bokoto** [comment] 2016-03-15 17:17
Hi Andrew - installing qt5-svg package  seems to have done the trick for now - I can change to Breeze, Oxygen. On the other hand Gnome, I am not quite sure if it displays the right icon as only one is listed in the icon folder : network-wireless.png. One more thing if i use the console to issue cmst -i I get the error : CMST - Cannot connect to the session bus. However the icon shows in the systray after that but notifications daemon is greyed out in preferences. If I change settings in preferences and exit without a reboot - next time i open the CMST interface it still holds the old settings. Does CMST save settings only after a reboot - correct me if i am wrong.

**Comment by andrew-bibb** [comment] 2016-03-15 23:37
Super on the qt5-svg working.  Until last night I did not know that there were icon theme packages which only shipped SVG icons. I'll add some notes in the Wiki page and also add in the optional dependency.

The gnome icon set does not sound as if it is installed properly.  There should be hundreds of icons in those subdirectories.  By the way, I was only using gnome for testing since freedesktop compliant icon themes have an inheritence property.  I just put the names in for the oldest one I could find, and all themes which derive from it should be covered.

The session bus error and notifications not working are related, in fact that error message is thrown from the constructor for the notify class.  The message is just what it says, QT could not make a connection to the session bus when the function was called.  How early in the startup process are you calling this?  I have to assume fairly late since you've got a terminal to type in.  The only connection we make to the session bus if for notifications.  All Connman stuff is on the system bus, but really odd we can make the connection to the system bus but not the session bus.  Next time it happens can you run `dbus-monitor --session` and see if you get any output.

The not holding settings is also very strange.  Settings are saved everytime CMST is closed, either by a shutdown, reboot, or manually exit.  The settings file is ~/.config/cmst/cmst.conf.   It is a plain text file in ini format so easy enough to look at.  Next time you exit and before a reboot can you check the file to see if it was updated for whatever setting you changed.  Also is it every entry or just one you've noticed?  If only one which one is it - I may have neglected or bypassed reading that setting starting up.

**Comment by bokoto** [comment] 2016-03-16 08:58
Thanks for the exhaustive response! The session bus error occurs only if i type cmst -i to change theme in the terminal. On the settings , i have noticed a couple of times that icon theme settings  (if theme name is entered in the box) would not hold on exit. That's why I had to do it through the terminal - and this is when the session bus error came up. I will do some more customizing and will let you know if anything pops up unexpected.

**Comment by bokoto** [comment] 2016-03-16 11:11
Something odd - settings don't change even after a reboot if i use the preferences box. I need to modify the cmst.conf file and then it holds. I am not sure what is going on - i even re-installed cmst just to be sure it is not messed up or something. I am sure it didn't work before for the theme settings that's why i needed to use the console but it seems it doesn't work for any other configuration options either - what could be wrong here?

**Comment by andrew-bibb** [comment] 2016-03-16 11:41
I'll do some testing (try to make it break) this evening. Can you tell me exactly how you are starting the program when you don't start from the command line.  If you are using a .desktop file what is the exact command in the file?  When you say "exit", how exactly are you exiting?  Is the program minimized, do you actually exit the program, is it a power off?  

When you you type `cmst -i` in a terminal is that all you type, or do you then append a theme name?  If you append the theme which one?  Either form works, but the -i alone will only use a systemwide theme if one is defined.  That is typically for people who are running a DE of some sort.  The -i _themename_ variant is for people running a bare system without a theme manager or the odd case of someone running a DE but for whatever reason they want a different icon set in CMST.  I'm asking because I want to try and duplicate the behavior at my end.  

Actaully while I'm on it, how is your system configured?  Are you running a DE and if so which one?  Which distro?  I have in the past set up a duplicate environment in a virtual machine, it is sometimes real helpful to track these odd issues down.  If you are not running Arch it takes a day or two to get everything set up, but I've always been able to do it eventually. In the VM I keep a basic Arch install up to date so it is somewhat faster if that is your distro.

**Comment by bokoto** [comment] 2016-03-16 12:49
I am running CMST alongside xfwm4 manager on LxQT siduction. The application starts through autostart/ cmst-autostart.desktop file:

[Desktop Entry]
Type=Application
Version=1.0
Name=Connman UI Setup
GenericName=Network Configuration
Comment=QT GUI frontend for connman
Categories=Settings;System;Qt;Network;
Icon=preferences-system-network
Terminal=false
Exec=cmst
StartupNotify=false
X-GNOME-Autostart-enabled=true
Name[de]=Netzwerk-Konfiguration.

So far nothing wrong - once it has loaded it picks up my wireless and shows the theme icon. The problem starts when I try to edit the preferences tab - I just cant make it stick. I normally toggle the Maximize/Minimize button to show the cmst interface. To try and save settings i normally use the exit button which closes the app. The X button minimizes the interface - which i believe is how it should be. I am unable to apply any themes thru the settings interface - I can only force cmst -i (theme name) and then the icon shows up in the tray regardless of the session bus warning. For changing any other setting i need to edit the conf file directly otherwise changes are not saved even after a reboot ( apart from cmst -i which is propagated thru the console and seems to works). I have no problem changing any appearance settings in the DE - I ve tried 4-5 different themes so far and they all show correctly. Typing only cmst -i in the console ends up displaying the same session bus error and doesnt' seem to change any settings within the preferences box ( still displaying old theme icon) but overrides the icon in the system tray and brings up the system wide icon for the wireless.
So this is in a nutshell - will stick around if you have more questions. Thanks

**Comment by andrew-bibb** [comment] 2016-03-16 13:32
Thank you, this will give me a bunch of information to work with.

Autostart file is fine. I was wondering if there were some command line options being given as they will take precedence over the settings. You are actually seeing that when you use the -i option, but I've no clue why doing so would make the session bus not be found.  That is so wierd it may be a programming thing from my end so I'm going to go through the code in that section line by line.  

I'm actually supposed to be doing work at the moment so I can't spend a whole lot of time right now. If you've got a minute exit CMST and then delete the entire ~/.config/cmst directory.  Restart CMST and see if the settings stick.  It is almost sounding a bit like a permissions issue on writing the settings file, but that makes no sense if you are autostarting from your user account and editing the file from your user account works.

**Comment by bokoto** [comment] 2016-03-16 15:37
Bingo! Deleting the whole cmts config. folder fixed the saving issue. Now it accepts changes as expected on pressing the exit button. But here is the kicker : once I do cmst -i from the console - i end up with the same problem again...for some reason the cmst settings get corrupted when i do the cmst -i command and i cant save anything again.....ok for now i will keep playing with this and see if anything falls thru the cracks..

**Comment by andrew-bibb** [comment] 2016-03-16 22:53
To be sure I understand.  Typing `cmst -i` alone causes the problem with settings not sticking and the dbus error, but `cmst -i <theme-name>` works properly?  

I kind of hope so as I just went through the code and can't find any reason the settings would not stick and the dbus call throws an error, but if the above is true i think I can identify the exact line.  If so I may be able to isolate and put an if statement around it.

By the way, I've tried every combination of -i with and without names and with names I know are invalid and I can't reproduce.

**Comment by andrew-bibb** [comment] 2016-03-17 00:55
I just uploaded some code with a possible fix to this issue.  The way the code used to work I always set the theme name to the value on the command line or in the preferences text box, which both could be blank.  On my system blank text sets the icon theme to hicolor.  That default comes from QT, not me.  It occured to me though, what happens if someone does not have hicolor installed, so I've revised the code to always provide the internal default theme name if none is provided and if the current theme name returns a blank string. Out of curiosity, do you have the hicolor theme or package installed?   

I don't know if this will work, but if you could possibly try it out it would be handy.  I'm still not sure how this effects the notificaton daemon, unless it puts QT into an error state internally.

**Comment by bokoto** [comment] 2016-03-17 10:42
Hi Andrew, both cmst -i and cmst -i >icon theme< result in dbus session error.  I have the hicolor package installed. I will try again later today and let you know.

**Comment by andrew-bibb** [comment] 2016-03-17 12:00
Probably not worth your time if both -i and -i <icon-theme> result in the same error.  I'll leave the code in as it is not wrong and I probably should have done it that way initially.

Do you get the error if you set the icon theme in preferences, or is it only if you do it from the command line?

**Comment by bokoto** [comment] 2016-03-17 12:32
I get it only from the command line - the preferences box works fine and saves the icon theme now, so I see no need know to use the console unless I have to reproduce the error.

**Comment by andrew-bibb** [comment] 2016-03-17 16:12
OK then, that tells me I'm looking in the wrong place.  I need to look somewhere in the commandline parser, not in the code where I define the icon theme.

**Comment by andrew-bibb** [comment] 2016-11-25 15:32
I've been playing with is on and off since March, most recently a fair amount today.  I'm afraid I can't duplciate it at all.

I was going to close this out, but please reopen if you feel we need to keep at it.

**Closed by andrew-bibb** 2016-11-25 15:32 UTC
