### ISSUE TITLE
Support symbolic tray icon with different signal strengths

### ISSUE THREAD

**Issue by kminh** [andrew-bibb/cmst#98] opened 2015-04-23 05:57 UTC
It would be great for CMST to support symbolic tray icon with different signal strengths, similar to how Network Manager's tray icon is implemented in many Gnome-based themes.

As per the previous discussion: https://github.com/andrew-bibb/cmst/issues/95, best to have an option to:
- use symbolic tray icon with different signal strengths
- (or) use symbolic tray icon without different signal strengths (just wired or wireless)
- (or) use the built-in icon

Thanks for consideration.

**Comment by andrew-bibb** [comment] 2015-06-28 21:14
Well this is embarassing.  Got the icon manager written and debugged, found and fixed several issues with notify.cpp and Dunst, and then deployed the icon manager to work on this issue and discovered I could really have done it by changing 2 lines in the code.  Reason being that all of the icon themes I've looked at really use the same symbol for the wireless strength.  They call it different things, but images are all basically the same.  I probably could have just used the ones hard coded into the program and I'd bet no one would have noticed.  Oh well, I really needed this for my media player anyway and I'm also glad I fixed the Dunst issues.  

Code is now in the master branch, it will be incorporated into the next official release.  When you run the first time a new file will be created: HOME/.config/cmst/cmst.icon.  In there are entries for wireless icons for Adwaita, gnome and oxygen.  The way it is written it is easy enough to add entries any other themes people want.  This formulation also allows one to change theme icons for your own use.  I need to do a whole lot of documentation (wiki page) and add comments to the cmst.icon file.  The order of selection is:

If called without the -i switch then hard coded icons are used
If called with the -i switch then the following order is used until one is found 
1) If specified the icon name associated with the theme
2) if specified the freedesktop.org named icon (key fdo_name in the file)
3) resource defined in the users cmst.icon file
4) icon hardcoded into the program

If you could try it out and let me know how it works, or if you find any bugs I'd appreciate it.

**Comment by kminh** [comment] 2015-06-29 05:14
I'm trying the master branch (via https://aur.archlinux.org/packages/cmst-git/) but it doesn't seem to work, or I could be doing something wrong.

I changed `icon_theme` in `cmst.conf` to `gnome`, restarted cmst but the hardcoded icon was still being used. Does the fact that I'm using Cinnamon with Numix-Circle icon theme (https://aur.archlinux.org/packages/numix-circle-icon-theme-git/) affect the selected icon?

Thank you for all the work done.

**Comment by andrew-bibb** [comment] 2015-06-30 00:36
You're not doing anything wrong.  I put in the theme icon names from one of the posts in issue #95 without checking them.  The names wern't quite right, had to add -symbolic at the end of each icon name in gnome and Adwaita.  I don't have oxygen installed on my system so the names there may not be right either, if you've got a way of checking I'd appreciate it.

Current version 15.06.29-2 has a new icon definition file. You must delete the cmst.icon file in your HOME/.config/cmst directory before trying the new version.  If the file exists it will not be overwritten.  

Thanks for sticking with this one.

**Comment by kminh** [comment] 2015-06-30 08:29
It's working now, thank you.

**Possible improvement**

Since we have icon theme inheritance, for example Numix Circle inherits from Numix while Numix inherits from gnome, is it possible to not specify a `Numix` entry in `cmst.icon` file? That means if I set the icon theme to `Numix` it should use gnome's icon name (for e.g. `network-wireless-signal-none-symbolic`) but of course use the actual icon from Numix theme. This is to avoid duplication in `cmst.icon` (Adwaita, Numix, and gnome both use the same icon names).

To make things easier there can be a fallback icon theme (set in `cmst.icon`) that is used when an icon entry is not found in `cmst.icon` file, that way we don't have to care about inheritance at all.

**Comment by andrew-bibb** [comment] 2015-06-30 22:42
Actually the idea was that you would put in an entry for your theme, in this case `Numix`, into the `cmst.icon file`.  Then CMST would use the named icon from the `Numix` theme.  I was figuring each user could do that for their own themes and if someone wanted to do a pull request for a specific theme I'd build it in.

That being said, I did not know about icons and inheritance.  I'm not as particular as some Arch users, but all in all my system is pretty bare bones for the eye candy.  I did some reasearch on icon inheritance and it seems that to follow the Freedesktop specification that programs that use it must fall back through the inheritance tree if an icon in a specific theme can't be found.  I use internal QT functions to check whether or not an icon exists and I can't find anywhere they specifically say they follow this specification.  They are typically pretty good so I'm guessing (hoping) they do.  

I'm going to assume for now that they do and rework the iconmanager. It should vastly simplify the whole thing.  All I'll need is a single list of fallback names for each one instead of spearate entries for each icon in each theme.  Just need to iterate through the list until one matches and return it.  It is raining here (yet again) so I may get this busted out this evening.

**Comment by andrew-bibb** [comment] 2015-07-01 01:00
Got it cleaned up and uploaded.  Again remove the cmst.icon file from your HOME/.config/cmst before running.  Now all the possible theme names are supplied in one line separated by commas for each icon.  We go through that comma separated list looking for an icon in that theme.  Any theme that inherites from gnome should now work with the list provided.

Still set up so that anyone can add names for other themes or modify the icon names in their own HOME/.config/cmst/cmst.icon file.  By modifying names they can get whatever icon they want to appear.

**Comment by kminh** [comment] 2015-07-01 03:58
Got it reinstalled again and is working great. All I have to do now is select "Use icon theme" and then type in "Numix".

We might take a step forward and auto detect the current gnome theme as well, when the desktop environment is gnome-based of course.

Thanks for all the work done, please close this issue if needed.

**Comment by andrew-bibb** [comment] 2015-07-01 15:23
I still want to add a huge number of comments into the cmst.icon file and add a wiki page here so I'm going to keep this open until I do that.  I find the issue tracker to be a real handy "to do" list.  

For auto-detect it should already be built in.  If you have a system wide icon theme installed (and I'm guessing you do), all you should have to do is select "Use Icon Theme", it should not be necessary to fill in the text box as QT will detect the system wide theme and use it.  The text box is for people like me who have no theme manager installed but may still want to use an icon theme.  The text box also allows you to override the system wide theme with another of your choosing (for CMST only).  Not sure why someone would want to do that, but you can.

I've used the word "should" a lot above because recently the QT guys changed a lot of things with icons and themes.  That is the way it used to work inside CMST so I'm assuming it still does.

**Comment by kminh** [comment] 2015-07-02 01:24
Ah I see, it's auto-detecting my icon theme as well. Great work, thanks again.

**Comment by andrew-bibb** [comment] 2015-07-04 00:05
File is commented and Wiki page is up so I'm going to close this now.

**Closed by andrew-bibb** 2015-07-04 00:05 UTC
Labels: enhancement

**Comment by bokoto** [comment] 2016-03-14 17:44
Hi Andrew, I know this is a closed one but i am trying to get CMST to work with a different wifi icon theme in Lxqt and following the instructions above. I am running xfwm4 and using Breeze theme as system wide theme. All desktop icons change correctly but the CMST wifi icon remains the same ( hard-coded ). I cant locate any cmst.icon file anywhere. The only other icon that CMST will accept is Faenza but it remains grey and won't change color thru the colorize option. I have tried setting the icon theme from the cli too - to no avail. So far I have tried Breeze, GNOME, Oxygen, none of them working with CMST. What is it that I am missing? Thanks.

**Comment by andrew-bibb** [comment] 2016-03-14 23:08
Do you have the qt5-svg package installed?  If you don't my first suggestion would be try that.  Currently the icon manager looks for system theme icons based on the theme_names= line in your post above.  The extension is not hardcoded, but as I mentioned, by default svg support is not provided using a bare installation dependency list.  If you don't have the qt5-svg package installed and installing it works could you let me know and I'll add it as an optional dependency.  If you do have it installed I may need to look at the code again, but as I said, the file format and extensions are not hard coded.

Based on what I'm seeing in the Breeze icon file list you should not need to modify the icon file.  It is already covered.  Also try to check /usr/share/icons/breeze to make sure that network-wireless-connection-00.svg (and the others) exist there somethere.  

Colorizing only works for the internal icons.  That is by design because the only icon set I know anything about is the internal (Awoken) set and it is meant to be colorized.  

For supplying the icon name at the command line, or from the preferences tab, the name is case sensitive.  Basically it has to match the direcotry name under /usr/share/icons.  As installed on my local system the names would be: oxygen, gnome, Adwaita.  Note capital A in Adwaita.  I haven't tested any others, but I just looked at these three again and they pick up the theme icon properly.

To continue this discussion could you do me a favor and open up a new issue on it.  Reference back to this one if you want to.  Doing that just keeps things cleaner.  I saw your other post regarding resume and no wifi services and I will respond, but maybe not this evening.  This time change has killed me and I'm barely keeping my eyes open at the moment.  

Thanks
A-
