### ISSUE TITLE
Tray context menu entries

### ISSUE THREAD

**Issue by fguzm** [andrew-bibb/cmst#117] opened 2015-10-12 04:28 UTC
to scan and connect, to disconnect.
So there would be no need to open the window and switch the tabs.

**Comment by andrew-bibb** [comment] 2015-10-13 01:02
Just letting you know that I've created a local branch and am working on this.  

So far I've just cleaned up a lot of the existing context menu code to be more robust and clearer.  I've learned a few things about menus and QActions since I first wrote that piece of the code.

**Comment by fguzm** [comment] 2015-10-13 05:18
Ah cool, then I'm curious about what will come.

**Comment by andrew-bibb** [comment] 2015-10-15 01:24
I just uploaded changes to address this.  The tray icon context menu is quite expanded.  There are new submenus for Technologies and WiFi, and the old Info entries are now also in a submenu.  The submenus are kind of necessary as the items in these menus are created and deleted dynamically and isolating them in submenus makes that clean.

The entire menu is tearoff enabled.  It is now possible to have the menu live in its own window on your desktop and control major elements from there. Click the dotted line at the top of the menu to tear it off.

Also a bunch of tooltips on the entries.  These can be disabled from the Preferences tab, but they are controlled by Enable ToolTips (Interface), not Enable System Tray Popups.  I was considering tooltips on the context menu items to be part of the interface, particularly since it can be torn off and live separately from the system tray, but I might be able to be convinced otherwise if someone has a real good reason

**Comment by fguzm** [comment] 2015-10-15 04:59
Wow! It's like christmas.

**Comment by fguzm** [comment] 2015-10-18 05:44
Settings are overtaken after manually exit cmst only. (All settings)
Debian amd64

**Comment by andrew-bibb** [comment] 2015-10-18 14:41
The only one was the new option to colorize icons.  I saw that when I was working on it and just uploaded code to update the colors immediately.  All the options in the "Start Options" groupbox only take effect at startup, but that is by design because they are start options.

I'm going to close this thread as I believe it is solved. If there is some setting not taking effect on your machine which think should be set immediately please feel free to open a new issue about it. 

By the way, meant to thank you for the suggestion that started this thread.  When I started the program I had these vague ideas about what the tray icon and menu could do (the ST in CMST stands for system tray), but when it came time to write that part I couldn't actually think of what I really wanted the icon menu to do.  It is much more polished and complete now.

**Closed by andrew-bibb** 2015-10-18 14:41 UTC
