### ISSUE TITLE
In Wireless tab, connected/unconnected indicators are too similar

### ISSUE THREAD

**Issue by dnlopez** [andrew-bibb/cmst#158] opened 2016-11-04 21:40 UTC
Having used cmst for about a month now, I'll give you first my casual, unthinking impression of this issue up to now - on looking at the Wireless tab to see what I'm connected to, I find myself slightly bewildered. Staring at the screen for a few seconds, I think I've sometimes assumed that the one with the heart under 'Favorite' is where I'm connected - but I feel disquiet, because I know that 'favorite' is a different concept to 'connected', really. So, I then may select a network and click 'Connect' just "to be sure", though I may be connected to it automatically already. Ultimately I never feel quite sure if I'm connected until I open the browser and actually try to visit a website.

Today I stopped for longer to try and get past my confusion properly. I've finally noticed that the icons that appear in the 'Connected' column are not all the same. See my screenshot - the top one meaning 'connected' is very similar to the others that mean 'not connected' - you have to look quite carefully to see the little 'X' on the latter. This column does have exactly the information I wanted, but I think all this time I've just been seeing those icons identically, a generic 'network' icon for decoration.

I'm running XFCE and don't tend to tinker much with the themes, but I looked at what icon themes I have installed: Adwaita, Oxygen, GNOME and HighContrast. The one in my screenshot is Adwaita. I temporarily tried the others and, well, they're not much better. Even in 'HighContrast' the two states look way to similar, IMO. Trouble is they all follow the same idea of adding a little X to the 'connected' icon, instead of fundamentally changing the icon's shape. The Oxygen one is best - it at least uses a little colour, some red in the X helps it to stand out - it's still very tiny though.

None of this is your fault, so to get to the point, I think that if a network is connected then the program should draw the 'connected' icon the same as it does now, but if unconnected it should leave the cell blank. This would also be more consistent with the 'Favorites' column (else, why doesn't that show an outline or greyed-out heart on all the networks which aren't favorites? Not that I want that. Better to leave it blank, IMO. I've never had any problem interpreting the favorites column, regardless of how hard I'm thinking or squinting).

Besides this, thanks for a lovely program in all other ways.

![cmst](https://cloud.githubusercontent.com/assets/4549132/20023316/39cd2850-a2d7-11e6-9cde-524fcd44c7fc.png)

**Comment by andrew-bibb** [comment] 2016-11-06 16:07
First off thank you for using the program and for the detailed question.  Just back from some whirlwind trips through 2 provinces and 4 states, so starting to get caught up on things around here.

CMST is really just a front end to ConnMan, we don't try to hide or obscure what ConnMan reports, and I think some of your questions may relate to that.  The Wireless tab is really not for determining which service has a connection to the internet.  Because ConnMan manages any connection it can find (wired, wifi, cellular, bluetooth, VPN) the box you want to use to tell you how you are connected is the Services box at the bottom of the Status tab.  ConnMan will automatically rank all services it can find and connect to and they are presented in this box in the order ConnMan determines.  That being said, it is possible to configure a system so that the only possible connection is Wireless, then Wireless and the Services box in Status would show the same things.

Favorite is another ConnMan thing.  In ConnMan it only means that you have on at least one occasion made a successful connection using that particular service.  ConnMan uses that property internally to help rank services in order.  In the Wireless tab ConnMan will show all WiFi services it can connect to. You may notice that after some time that services will drop off the list, particularly if you are already connected to the internet.  I think ConnMan figures you don't want them so stops tracking them, but I'm not entirely sure on that.  One of the things that took me a while to get over in ConnMan is that there is no mechanism to edit or remove services (it is possible to do that manually if you have root access).  What shows up in the WiFi tab are the services available now, not a list of services you've connected to in the past.  In the Wireless tab is you click remove on a service all it does is remove the Favorite property from that service.

This may also be of assistance to you.  In Preferences if you have a check in the Enable ToolTIps (Interface) box then if you hover your mouse over the icon in the Connected column in the Wireless tab you will get a popup telling you the current connection state of that service.  Of course if you only have a laptop with touchpad that is a royal pain.  It would though at least save you from hitting connect on an already connected connection. By the way, if you set Autoconnect (The Configuration button lower right corner of the Details tab - the General box of the properties editor which will popup) then you will be automatically connected to that WiFi service if you can be.  If you have more than one service with AutoConnect available then ConnMan will do its own internal ranking and connect to the one it thinks is best based on quality of the connection or signal, encryption type, etc.  The idea in ConnMan is that once you've made a connection you really should not need to worry about it again, let the deamon deal with it.  

Lastly, there is quite a lot of icon customization you can do.  I'd refer you to this page in the wiki: https://github.com/andrew-bibb/cmst/wiki/Icons-and-Icon-Themes 

I'm linking that so that you can look through to see if it does what you want, but I'm going to leave this issue open and please hold off doing any mods to your icon file just yet as I think there may be a problem in that code.  Issue #157 has identified a problem in something I know was working, so I'm pretty sure I broke something somewhere and in trying to track that down I'm also seeing some other odd behavior in the icons.  I don't want you to waste your time doing a mod to your local file if I change it around.  I'm not sure that the problem is there, but it would be prudent to wait until I can get everything fixed.  Once I get that fixed I'm thinking of adding another flag to the icon definition file for grayed out which will allow one to do exactly what you are requesting.  I'll close this issue out once I'm sure everything is working.

**Comment by dnlopez** [comment] 2016-11-07 02:00
Thanks for your thorough response. It's true that I'm fairly new to ConnMan itself also so this was useful information, and I appreciate that CMST reflects its design without hiding things that would narrow its capabilities.

My first port of call will be the Services box in future. Also I ticked "Enable System Tray Popups" in Preferences and now there's a handy tooltip on the tray icon which seems to tell me which wifi service I'm connected to. And in the "WiFi Connections" on the tray right-click menu there's a tick next to that service too. So that's all great.

I present my earlier experience in being drawn to the Wireless tab and looking where I did, just as an anecdote, knowing that I was playing dumb a bit. I don't know if other people would approach it the same way, who knows.

I still reckon the non-connected services should show nothing at all in their 'Connected' cell (not just X'ed or greyed!). I thought of another reason why. In my memory, that "two computer screens" icon comes from Windows - I think it was Win95 when I first saw it, on their systray, denoting a LAN. People change their LAN settings relatively infrequently, and expect them (as long as the cable's plugged in) to be connected all the time, so if it's not, it's useful for the icon to be there with a red X on it as a warning that it's broken. With Wifi on the other hand, the majority of networks I come across I'm never going to connect to, and that's not because they're broken, they're just not meant for me. I feel like an icon with an X implies some kind of improper breakage that isn't really true (and in other themes, for example there's one that looks like a cut cable, also implying something broken).

I mean, to really take this logic all the way, perhaps the 'favorites' which are unconnected - ie. those which were previously connected once but aren't now - should show a 'broken' connection icon, and non-favorites only show blank. Though if this were my program, then personally just to make it easier on the eyes, I'd fudge it that only the connected services show an icon and that's that.

Also, responding to what you said about the 'Remove' button I don't think it would be a bad thing if you changed the text on that to 'Unfavorite', if you wanted to.

**Comment by andrew-bibb** [comment] 2016-11-25 16:18
I've been mulling this over and I don't totally disagree, however with some icon themes I think it is much less of an issue. Code to address this has been uploaded here and what I've done is split the difference.  By default the behavior is as it always was.  If you are running a theme where the icons are similar (for instance your Adwaita example where they really are), or if you don't want to see icons in the connected column in the wifi tab then there is a new icon in the local icon.def file.  Icon is called "wifi_tab_state_not_ready" and I've added some comment lines explaining how to use a blank icon.  When set there will be no visible icon, but if you hover the mouse over the space where it is you'll still get the status popup.

There was an unrelated issue with the theme icons in the wifi tab not displaying properly.  Sometimes they did, sometimes they didn't.  That should be fixed as part of the issue 157 fix.

About the Remove button, I called it that becasuse that is what the method is called in ConnMan.  There are some people who come here from using the connmanctl commandline interface, so trying to keep it as familiar as possible.

**Closed by andrew-bibb** 2016-11-25 16:18 UTC
