### ISSUE TITLE
Unable to find systemtray on LXQt

### ISSUE THREAD

**Issue by gen2brain** [andrew-bibb/cmst#101] opened 2015-05-24 10:25 UTC
LXQt is compiled against Qt5.
I have a mix of tray apps, GTK+, Qt4 and Qt5 and they all work correctly with lxqt-panel systemtray.

**Comment by andrew-bibb** [comment] 2015-05-24 15:42
I'm afraid I can't duplicate this.  I installed LXQt into a virtual machine and ran CMST.  First with no icon theme installed, then with the Oxygen icon theme installed.  Both times the tray icon showed just as it is supposed to.  Screen shot below (with the balloon popup)
![image](https://cloud.githubusercontent.com/assets/6935544/7788467/ce98ca9a-0209-11e5-8e25-c6ae929488ee.jpg)

**Comment by andrew-bibb** [comment] 2015-05-25 00:14
I was thinking about this some more, and particularly the title.  Did you get a message box popup saying that CMST could not locate a system tray?  If you did it is caused by starting CMST before your DE has created a system tray.  Solution is simple, just start CMST with the -w option.  This will instruct CMST to wait the specified number of seconds before trying to place an icon in the tray.  For example:
`cmst -w 5` or `cmst -w 10`

Alternatively you could start up CMST later in the startup process, but I added the -w option specifically so people didn't need to mess with their startup order.

**Comment by hagabaka** [comment] 2015-05-25 01:50
On my LxQt system I have to use `-w 20` to get systray icon with CMST autostarted. LxQt has a feature to wait for systray to be available before autostarting an application (`X-LXQt-Need-Tray=true` in autostart .desktop file), but that doesn't work in my experience.

**Comment by gen2brain** [comment] 2015-05-25 05:44
No, CMST is not in autostart, I start it manually and tray is available at that time. I tried both xfce/mate options.
I use Gentoo with LXQt on two laptops and they both behave same. Qt version is 5.4.1 . I tried also to change this line https://github.com/andrew-bibb/cmst/blob/master/apps/cmstapp/code/control_box/controlbox.cpp#L1865 to just if (true) , then error messagebox is not shown, but still no tray icon. 

I tried to compile Qt4 systemtray example, and that works, but I can't find similar example for Qt5. I can probably rewrite that example in PyQt5 if that make sense. Is there anything else I can do to try debug this?

**Comment by gen2brain** [comment] 2015-05-25 06:47
I managed to compile qt-systray-example like this:

# git clone https://bitbucket.org/aarmea/qt-systray-example.git && cd qt-systray-example/
# sed -i 's/QtGui/QtWidgets/' main.cpp window.cpp
# /usr/lib/qt5/bin/qmake && make
# ./systray

That basic example doesn't work. And I was wrong, I actually don't have any running Qt5 tray app, just Qt4 and GTK+. So it is not related with CMST.

**Comment by andrew-bibb** [comment] 2015-06-12 00:43
Sounds like we're done with this so I'm going to close it.

**Closed by andrew-bibb** 2015-06-12 00:43 UTC
