### ISSUE TITLE
WIFI remains disabled on wakeup

### ISSUE THREAD

**Issue by flamusdiu** [andrew-bibb/cmst#132] opened 2016-02-19 18:19 UTC
I have noticed that when I close my laptop when I am connected to a WIFI access point, when I wake it up later, it keeps the WIFI disabled. I have to manually enable the WIFI again.

I can probably get some logs about this if you let me know what is needed but a very odd issue and only one I've noticed since the last update.

**Comment by andrew-bibb** [comment] 2016-02-19 20:00
When you say "manually enable the WiFi" do you mean turn it on in the technologies box on the first tab?  I'm not sure if you are referring to that or if you mean it is related to your other issue where you're not getting an autoconnect.

**Comment by flamusdiu** [comment] 2016-02-19 23:34
Yes, that's when I mean, some reason it's disabled even though when I closed my laptop and it was enabled. This one and #133 are two different issues. Not sure if they are actually related.

**Comment by andrew-bibb** [comment] 2016-02-20 01:12
I think this is something related to the way your computer is set.  There is nothing in CMST, and I don't believe there is anything in Connman which powers off a technology when the lid is closed. 

You can power off a technology (and power on as you've discovered) from the first tab, using the powered buttons or the "All Devices Off" checkbox in the upper right.  Both are manual control only, there is no automatic way to do it from CMST (and I don't recall ever seeing anything like that in the Connman documentation).  

It sounds a bit like your system is doing an rfkill when you close the laptop lid, and maybe not  reversing that when you open the lid.

**Comment by flamusdiu** [comment] 2016-02-20 03:59
Very odd ... oh well, I didn't change wifi settings but I'll look into it.

**Comment by andrew-bibb** [comment] 2016-02-22 01:49
I know you closed this issue, but I just stumbled across this forum thread:

https://bbs.archlinux.org/viewtopic.php?id=203404

If you've got a Dell maybe something to look into.

**Comment by flamusdiu** [comment] 2016-02-22 14:35
It's a Lenovo Y50. I'll take a look though when I can.

>

**Comment by bokoto** [comment] 2016-03-14 12:41
I have exactly the same problem as described. After resuming, connman does not auto-connect to my wifi - I have to toggle the wifi on/off button. However I do not get a password prompt. Sometimes the toggle button works and the connection is established within a second. However most of the time if i try the toggle workaround, the connection status under wireless tab will switch from "idle" to"association" then back to idle and this just goes on and on. I have an HP elitebook and the rfkill list shows no wifi blocks. Alternatively trying "systemctl restart connman" returns an error.Of course rebooting will fix the issue however rebooting after each resume is hardly a solution.

**Comment by andrew-bibb** [comment] 2016-03-15 23:46
If you are getting the 1 Found and 1 Powered label on the WiFi tab this is not at the technology level, rather the service level.  I'm going to go back through the connman developer mailing list to see if I can find anything that looks promising.  

Next time that happens instead of doing the power toggle can you try the "rescan" button.  That will force Connman to query wpa-supplicant for wifi services.  I have a suspicion the problem is somewhere at that interface.

**Comment by flamusdiu** [comment] 2016-03-16 02:26
@andrew-bibb I have had zero luck with the "rescan" button. I thought it was just my computer (yeah, bad, bad me). It just gives me an error that dbus response timed out (I think -- not on the laptop atm). I usually bounce the wifi interface instead of hitting that button.

**Comment by bokoto** [comment] 2016-03-16 19:56
rescan button returns : 
Error Name: net.connman.Error.Failed
Error Message: Device or resource busy

This is driving me crazy - 2 out of 5 times the connection will go to: ready - online - connected 
and the rest of the time it shows: idle - associations - failure and then going round in circles. Strange It never picks up the connection automatically after a resume/hibernate. I always have to toggle the wifi on/off. Apart from that, after a reboot it always pick it up fine. This just beats me.

**Comment by bokoto** [comment] 2016-03-16 20:38
well, well well - this is a trial and error  job...just ran out of ideas and decided to disable my lan adapter in the BIOS settings - guess what, now wifi resumes automatically after sleep and hibernate - so for some reason connman was probably trying to switch to my lan even though it was always off in the settings....go figure - problem solved ....

**Comment by andrew-bibb** [comment] 2016-03-16 23:09
Well that is interesting. Glad you found it, I never would have found a BIOS setting.

By the way, Connman really does not do much connection wise.  All it really does is communicate with your installed network sevice programs (wpa_supplicant, ofono, openVPN, etc).  Minor difference, but sometimes makes tracking things down hard since Connman is only reporting what it is being told by these other programs.

**Comment by bokoto** [comment] 2016-03-17 10:16
yes, that was a shot in the dark to try the BIOS but it really worked. So I am curious to know if that fix would work also for flamusdiu who initially opened this issue. I have an HP elitebook so lets see if this will work for other laptops too.

**Comment by andrew-bibb** [comment] 2016-03-17 23:31
Now that is is working you probably don't want to play with it, but in the event I'm wrong I'm wondering what would happen if you turned the BIOS settings back on and powered off the ethernet wired connection from CMST.  Strangely enough when Wifi does not work we look at the wifi settings, not the ethernet settings.

**Comment by flamusdiu** [comment] 2016-03-17 23:43
@bokoto I'll have to try it when I pull my laptop back out. I have been playing with Remix OS lately but I'll try tomorrow.

**Comment by bokoto** [comment] 2016-03-18 01:15
Andrew ,will try that tomorrow but I will leave the Lan/Wlan switching off - it might be the main accomplice here. So far with the lan switched off - cmts and connman are pretty stellar - no dropped connections - quite fast on resume, no stuttering, no scary dbus messages anymore.

**Comment by bokoto** [comment] 2016-03-18 17:36
Ok so here is the score : It is the Wlan/Lan Switching option in BIOS that causes the problem - if it is on, I get no wifi on resume ( exactly as described in the beginning of this post). In addition, if LAN alone is on in the BIOS, this doesn't cause any issues. Now to summarize the results of today - WLAN/LAN switching causes Connman to somehow try switching to wired upon resume even though LAN is off in its own settings ( I have not seen any wlan/lan switching controls in cmts and probably no such in connman too). I guess this is what the folks from connman should probably look at - I don't know if it is a hardware specific thing  - my wireless is Intel AGN 5150 and the ethernet is Intel 82567LM. I have two more distros running on the same laptop and I ve had zero issues with wifi on resume with them. However they run different network managers. Next on the interface topic. Rearranging the wifi connection order in the service tab with move before/after doesn't work for me. So if i have two networks in range, connman always connects to the first one in the queue...and currently i am unable to change that thru the move after/before button.Same after resume, even if before suspend I am connected to the 2nd wifi in the queue, upon resume connman will always try and  connect to the first one on the list and not to my last successful connection.

**Comment by andrew-bibb** [comment] 2016-03-18 22:36
This probably gives me enough post a bug report on Connman.  

The move before and move after are actually kind of useless.  I put those in there before I realized what they did (or more accurately didn't) do.  They will reorder services, but only if they are already connected.  They also won't hold across boots or on a resume from suspend/hibernate. 

After I put them in I found a very long document in the Connman source tree explaining the logic of determining a service order, how it is done automatically and how it cannot be changed.  I understand the reasoning, but lets leave it at that.  Had I understood that document before I put the move before and move after in I probalbly would not have done it, and I've thought on several occasions about removing the controls.  

One thing I could do though is revise my code to only list services which could be reordered.  Currently I list all known services without checking to see if they can be changed.  

If you are in an area where you'd rather have a weaker signal (or security - both are taken into account for determining service order) be the primary service, you need to remove the favorite property from the one you don't want.  That can be done in the wifi tab using the remove button.  I made the button name the the same as the dbus method called, and it may be a bit confusing.  Remove removes the favorite property, not the service.  After a revove the service will still show up and you will still be able to connect to it, although once you do it becomes a favorite again.    

I was going to reclose this thread since the original wifi disabled on resume problem seems to be solved the best we can do.  If you want to continue on about the move before and after there are plenty of numbers still available for new issues.   

A-

**Closed by andrew-bibb** 2016-03-18 22:36 UTC

**Comment by bokoto** [comment] 2016-03-19 00:12
I personally consider the wifi resume issue done and dusted since there is nothing more you can do within your power when this is possibly a Connman issue with LAN/WLAN switching.
On the move before/after - it is not really that important as a few more clicks will get the job done. I posted that because in my area there are about 4 wifi spot i normally connect to and they all appear as favourites. The problem is that last night connman was trying to connect to the first one on my list and the connection was apparently down for some reason making connman throw erorrs all over the place  - it didn't even try to connect to the second or third favourite ones on the list, which were available and running. Not until I selected manually from the list. I mean automatic connection switching is something basic. Nowadays,this is really a must-have feature for a wifi connection manger. Thanks again for your help - I will stick around !

**Comment by andrew-bibb** [comment] 2016-03-19 00:58
Lets beat at dead thread a little more.

I went back through the connman developer mailing list and in February 2015 there was an exchange about move before/after not working.  The response from the developers was that the implementation was fundamentally broken and they were not sure it could be fixed.  Reason being the everytime there is an automatic service reorder it would overwrite the manual reording.  Should not be a problem from a connection point of view as Connman will never take down an online connection by itself, but everything below is fair game.  Just went through the Connman source code and it seems there are almost no services which can actually be moved. There are dozens of checks on the source and target services and all return errors.  Only after you make it through that maze are you allowed to move the service.  The scales just tipped again towards removing those controls, but going to sleep on it.

Connman is supposed to automatically fall back to another connection if it loses the online one.  I just tried as a check by pulling the ethernet cable and it fell right back to the wifi connection.  Something has to trigger a service reorder for that to happen, so I'm guessing whatever happened was not enough to trigger that.  Can't imagine what could cause that though.

**Comment by bokoto** [comment] 2016-03-19 01:33
I will do some more testing tomorrow - i still haven't tried ethernet + wifi - i will paly with it tomorrow a bit. You said that disconnecting the Ethernet cable switches over to the wifi - so I assume you have Lan/Wlan switching on by default - can you check that in your settings? Lan/wlan switching is normally on by default in almost all cases. It is more like a failover feature on hardware level, while  connection switching is not. So there might be additional variables that need to be set to trigger off an automatic connection switch. For example on my lenovo laptop - there are several options : best avaiallble network, a single connection mode by  wifi or Ethernet, turn off radio when switching location etc. All these features are  programmed in the connection manger. My concern is, are all these implemented in Connman and how we can control them. Without visible control options one could only guess and it gets very difficult to find a reasonable explanation as to why something happened or did not for that matter.

**Comment by andrew-bibb** [comment] 2016-03-19 17:13
I've got nothing remotely like that in the BIOS settings.  Two machines here, one Dell laptop and another fairly old self built desktop.  Only thing in BIOS on both is a switch to enable or disable the onboard LAN. 

I'm not aware of Connman being able to switch any of the things you are talking about on or off.  Connman automatically determines best available network which you see in the service sort order.  One of the design goals of Connman was to take all these decisions away from the user and only require user input on things they could not determine.  There are several papers around the internet explaining the philosophy.

I think some of this may be an LxQT thing.  I've got that installed in a VM, although with default OpenBox WM.  I notice every time I start up in LxQT all the technologies are off, even if I left them on when I exited.  This does not happen on any of my other VM's or real machines.

**Comment by bokoto** [comment] 2016-03-19 17:42
hmm wierd - i have Lxqt Manjaro with Openbox/Kwin running on my hard drive as well - no problems so far on connection management or switching with the default nm. I will try and install Connman to see if i can replicate your issues.

**Comment by bokoto** [comment] 2016-03-20 12:53
Unfortunately could not get Connman installed on my other LXQT distro. Will give it one more try today and if unsuccessful again  i will quit.

**Comment by andrew-bibb** [comment] 2016-03-20 13:21
I wouldn't spend a whole lot of time on it, but up to you.  I think it may be something with the session manager.  Currently I've got setups for: 
Real machines: 
Home built desktop Arch with i3 WM
Dell laptop Arch with i3 WM
VIrtual machines:
Arch with Enlightenment E20
Arch with XFCE
Arch with LxQT

Only on the last am I seeing the network come up turned off every time no matter what settings I have.  I was really trying to replicate the problems you were having with starting -i corrupting everything subsequent to that and not having any luck there either.
